// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOumNJXUSftjw7Qw_ndqL4tXitpEQWVZE',
    appId: '1:943871668803:web:50e08de7c4f32050a9daf6',
    messagingSenderId: '943871668803',
    projectId: 'traviaapp',
    authDomain: 'traviaapp.firebaseapp.com',
    databaseURL: 'https://traviaapp-default-rtdb.firebaseio.com',
    storageBucket: 'traviaapp.firebasestorage.app',
    measurementId: 'G-4PXXTGWQGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKvtwvbVgLYgBSyFmvmIU5K9QOSIb_SJY',
    appId: '1:943871668803:android:20cb7481b6d8e3aba9daf6',
    messagingSenderId: '943871668803',
    projectId: 'traviaapp',
    databaseURL: 'https://traviaapp-default-rtdb.firebaseio.com',
    storageBucket: 'traviaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc1UE4wsOAoFrEmbXqwC8L-OwSgggtoZQ',
    appId: '1:943871668803:ios:5ce4c03283321639a9daf6',
    messagingSenderId: '943871668803',
    projectId: 'traviaapp',
    databaseURL: 'https://traviaapp-default-rtdb.firebaseio.com',
    storageBucket: 'traviaapp.firebasestorage.app',
    androidClientId: '943871668803-0hsp7jefpbm4lngb0srds1fc0ek76v5q.apps.googleusercontent.com',
    iosClientId: '943871668803-e3iair7pv0mtr4kgb23a5bppnjl11f0a.apps.googleusercontent.com',
    iosBundleId: 'com.travia',
  );

}